# Generated by Django 3.1.7 on 2021-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210423_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='Description',
            field=models.TextField(max_length=300),
        ),
    ]
